apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: regular-traffic
  name: regular-traffic
  namespace: fake-traffic
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: regular-traffic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: regular-traffic
    spec:
      containers:
      - command: ["/bin/sh"]
        args: ["-c", "while true; do wget 'webapp.perfapp:8282/do_work?load_sync=80&load_async=80&ncpus_sync=1&ncpus_async=1&ops_sync=5000&ops_async=6000' -O /dev/null && sleep 30;done"]
        image: busybox
        name: busybox
        resources:
          requests:
            cpu: 20m
            memory: 128Mi
