apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: regular-traffic
  name: regular-traffic
  namespace: fake-traffic
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: regular-traffic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: regular-traffic
    spec:
      containers:
      - command: ["/bin/sh"]
        args: ["-c", "wget 'webapp.perfapp:8282/do_work?type=sync&load_sync=100&ncpus_sync=3&ops_sync=100000' -O /dev/null"]
        image: busybox
        name: busybox
        resources:
          requests:
            cpu: 20m
            memory: 128Mi
