apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: syncsvc
    app: perfapp
  name: syncsvc
  namespace: perfapp
spec:
  replicas: 1
  selector:
    matchLabels:
      service: syncsvc
      app: perfapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: syncsvc
        app: perfapp
    spec:
      containers:
      - image: arapulido/perf_app_load:latest
        imagePullPolicy: Always
        name: syncapp
        command: ["ddtrace-run"]
        args: ["flask", "run", "--port=5001", "--host=0.0.0.0"]
        env:
          - name: FLASK_APP
            value: "index.py"
          - name: FLASK_DEBUG
            value: "1"
          - name: DD_ENV
            value: "perftesting"
          - name: DD_VERSION
            value: "1.0"
          - name: DD_SERVICE
            value: "syncsvc"
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_ANALYTICS_ENABLED
            value: "true"
          - name: DD_PROFILING_ENABLED
            value: "true"
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: 800m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: syncsvc
    app: perfapp
  name: sync
  namespace: perfapp
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    service: syncsvc
    app: perfapp
status:
