apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: stress3
  name: stress3
spec:
  containers:
  - image: arapulido/stressng
    name: stress
    resources:
      limits:
        cpu: 1
        memory: "256Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
